-- MySQL Script generated by MySQL Workbench
-- Sun Sep 27 16:58:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema petShopVSG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petShopVSG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petShopVSG` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `petShopVSG` ;

-- -----------------------------------------------------
-- Table `petShopVSG`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petShopVSG`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `ciudad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petShopVSG`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petShopVSG`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `sub` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petShopVSG`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petShopVSG`.`vendedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`id_usuario` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `petShopVSG`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petShopVSG`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petShopVSG`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `description` VARCHAR(400) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `discount` INT NOT NULL,
  `created_at` TIMESTAMP  NULL,
  `updated_at` TIMESTAMP  NULL,
  `id_categoria` INT NULL,
  `id_tienda` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCategoria_idx` (`id_categoria` ASC),
  INDEX `idTienda_idx` (`id_tienda` ASC),
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `petShopVSG`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `petShopVSG`.`vendedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petShopVSG`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petShopVSG`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `remito` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  INDEX `id_producto_idx` (`id_producto` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `petShopVSG`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `petShopVSG`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
